# Generated by Django 3.0.6 on 2020-05-13 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Порода')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('note', models.CharField(max_length=256, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_num', models.CharField(auto_created=True, blank=True, max_length=256, null=True, verbose_name='Регистрационный номер')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата регистрации')),
                ('cage', models.CharField(max_length=10, verbose_name='Номер клетки')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type_of_animal', models.CharField(max_length=256, verbose_name='тип животного')),
                ('name', models.CharField(max_length=256, verbose_name='Кличка')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('photo', models.ImageField(blank=True, upload_to='pets_photo')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Breed', verbose_name='Порода')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_registration', to='app.Registration', verbose_name='Регистрационный документ')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Owner', verbose_name='Владелец')),
            ],
        ),
    ]
