# Generated by Django 3.0.6 on 2020-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type_of_animal',
            field=models.CharField(choices=[('DG', 'dog'), ('CT', 'cat'), ('PR', 'parrot')], default='DG', max_length=2, verbose_name='тип животного'),
        ),
    ]
