# Generated by Django 3.0.6 on 2020-05-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200515_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type_of_animal',
            field=models.CharField(choices=[('DG', 'собака'), ('CT', 'кошка'), ('PR', 'попугай')], default='DG', max_length=2, verbose_name='тип животного'),
        ),
    ]
